#ifndef PYTHONX_IR_H
#define PYTHONX_IR_H

#include "Python.h"
#include "pycore_ast.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PythonX IR: Python AST semantics lowered into PythonX-owned operations. */
typedef enum {
    PYX_IR_CONST = 1,
    PYX_IR_LIST, PYX_IR_TUPLE, PYX_IR_SET, PYX_IR_DICT,
    PYX_IR_NAME_LOAD, PYX_IR_NAME_STORE, PYX_IR_SEQUENCE,
    PYX_IR_SUBSCRIPT, PYX_IR_SUBSCRIPT_STORE,
    PYX_IR_GETATTR, PYX_IR_SETATTR, PYX_IR_DELATTR, PYX_IR_DELETE,
    PYX_IR_CALL,

    PYX_IR_ADD, PYX_IR_SUB, PYX_IR_MUL, PYX_IR_MATMUL,
    PYX_IR_DIV, PYX_IR_FLOORDIV, PYX_IR_MOD, PYX_IR_POW,
    PYX_IR_LSHIFT, PYX_IR_RSHIFT, PYX_IR_BITOR, PYX_IR_BITXOR, PYX_IR_BITAND,
    PYX_IR_INVERT, PYX_IR_POSITIVE, PYX_IR_NEGATIVE, PYX_IR_NOT,
    PYX_IR_LT, PYX_IR_LE, PYX_IR_EQ, PYX_IR_NE, PYX_IR_GT, PYX_IR_GE,
    PYX_IR_IS, PYX_IR_IS_NOT, PYX_IR_IN, PYX_IR_NOT_IN,
    PYX_IR_AND, PYX_IR_OR,

    PYX_IR_AUG_ASSIGN, PYX_IR_UNPACK, PYX_IR_STAR_UNPACK, PYX_IR_WALRUS, PYX_IR_ASSIGN_CHAIN,

    PYX_IR_IF, PYX_IR_WHILE, PYX_IR_FOR, PYX_IR_ASYNC_FOR,
    PYX_IR_BREAK, PYX_IR_CONTINUE, PYX_IR_RETURN,
    PYX_IR_JUMP, PYX_IR_JUMP_IF_TRUE, PYX_IR_JUMP_IF_FALSE, PYX_IR_LABEL,

    PYX_IR_FUNCTION, PYX_IR_LAMBDA, PYX_IR_YIELD, PYX_IR_YIELD_FROM,
    PYX_IR_AWAIT, PYX_IR_CLOSURE, PYX_IR_DECORATE,

    PYX_IR_CLASS, PYX_IR_SUPER, PYX_IR_PROPERTY, PYX_IR_DESCRIPTOR, PYX_IR_METACLASS,

    PYX_IR_LIST_COMP, PYX_IR_SET_COMP, PYX_IR_DICT_COMP, PYX_IR_GENERATOR,
    PYX_IR_COMP_FOR, PYX_IR_COMP_IF,

    PYX_IR_WITH, PYX_IR_ASYNC_WITH, PYX_IR_WITH_ENTER, PYX_IR_WITH_EXIT,

    PYX_IR_RAISE, PYX_IR_RERAISE, PYX_IR_ASSERT,
    PYX_IR_TRY, PYX_IR_EXCEPT, PYX_IR_FINALLY,
    PYX_IR_EXCEPTION_MATCH, PYX_IR_EXCEPTION_BIND, PYX_IR_EXCEPTION_CLEAR,
    PYX_IR_EXCEPTION_GROUP, PYX_IR_EXCEPT_STAR,

    PYX_IR_IMPORT, PYX_IR_IMPORT_FROM, PYX_IR_IMPORT_STAR, PYX_IR_IMPORT_AS,
    PYX_IR_GLOBAL, PYX_IR_NONLOCAL,

    PYX_IR_MATCH, PYX_IR_MATCH_CASE, PYX_IR_MATCH_SEQUENCE,
    PYX_IR_MATCH_MAPPING, PYX_IR_MATCH_CLASS, PYX_IR_MATCH_OR,
    PYX_IR_MATCH_AS, PYX_IR_MATCH_LITERAL, PYX_IR_MATCH_STAR,

    PYX_IR_FSTRING, PYX_IR_FORMAT_VALUE, PYX_IR_ATTRIBUTE,
    PYX_IR_SLICE, PYX_IR_STARRED, PYX_IR_NAMED_EXPR,

    PYX_IR_EVAL, PYX_IR_EXEC, PYX_IR_COMPILE,
    PYX_IR_TYPE_OF, PYX_IR_INSTANCE_OF, PYX_IR_SUBCLASS_OF,
    PYX_IR_HASH, PYX_IR_ITER, PYX_IR_NEXT,

    PYX_IR_NATIVE_CALL, PYX_IR_NATIVE_VALUE,
    PYX_IR_SAFEPOINT, PYX_IR_DEOPT, PYX_IR_GUARD, PYX_IR_PHI, PYX_IR_NOP
} PyXIROp;

typedef struct PyXIRNode PyXIRNode;

struct PyXIRNode {
    PyXIROp op;
    PyObject *constant;
    PyXIRNode *left;
    PyXIRNode *right;
    PyXIRNode **children;
    Py_ssize_t child_count;
};

typedef struct {
    PyXIRNode *root;
    PyObject *globals;
} PyXIRFunction;

PyAPI_FUNC(void) _PyX_IR_Free(PyXIRFunction *function);
PyAPI_FUNC(int) _PyX_IR_FromAST(mod_ty module, PyXIRFunction *function);
PyAPI_FUNC(const char *) _PyX_IR_OpName(PyXIROp op);
PyAPI_FUNC(PyObject *) _PyX_IR_Evaluate(const PyXIRNode *node, PyObject *globals);

#ifdef __cplusplus
}
#endif

#endif /* PYTHONX_IR_H */
