#include "Python.h"
#include "pycore_ast.h"
#include "pycore_pyarena.h"
#include "pythonx_ir.h"
#include "pythonx_backend.h"
#include "pythonx_native_ir.h"

typedef struct { PyObject_HEAD PyObject *globals,*name,*positional,*kwonly,*vararg,*kwarg; PyXIRNode *body; } PyXFunctionObject;
static PyObject *PyXReturnSignal;
static PyObject *pyx_function_call(PyObject *,PyObject *,PyObject *);
static PyTypeObject PyXFunction_Type={PyVarObject_HEAD_INIT(NULL,0) .tp_name="pythonx.Function",.tp_basicsize=sizeof(PyXFunctionObject),.tp_flags=Py_TPFLAGS_DEFAULT,.tp_call=pyx_function_call};
static int pyx_init_runtime(void){if(!PyXReturnSignal)PyXReturnSignal=PyErr_NewException("pythonx.ReturnSignal",NULL,NULL);if(!PyXReturnSignal)return -1;if(!(PyXFunction_Type.tp_flags&Py_TPFLAGS_READY))return PyType_Ready(&PyXFunction_Type);return 0;}
static void pyx_function_dealloc(PyObject *self){PyXFunctionObject*f=(PyXFunctionObject*)self;Py_XDECREF(f->globals);Py_XDECREF(f->name);Py_XDECREF(f->positional);Py_XDECREF(f->kwonly);Py_XDECREF(f->vararg);Py_XDECREF(f->kwarg);if(f->body){PyXIRFunction ir={f->body,NULL};_PyX_IR_Free(&ir);}Py_TYPE(self)->tp_free(self);}
static PyObject *pyx_return(PyObject*self,PyObject*args){PyObject*v=Py_None;if(!PyArg_ParseTuple(args,"|O",&v))return NULL;PyErr_SetObject(PyXReturnSignal,v);return NULL;}
static PyMethodDef pyx_return_def={"__pythonx_return__",pyx_return,METH_VARARGS,NULL};
static asdl_stmt_seq *one_stmt_seq(stmt_ty st){asdl_stmt_seq*s=PyMem_Calloc(1,sizeof(*s));if(!s)return NULL;s->size=1;s->elements=PyMem_Calloc(1,sizeof(void*));if(!s->elements){PyMem_Free(s);return NULL;}s->elements[0]=st;return s;}
static int compile_stmt(stmt_ty st,PyXIRNode**out){asdl_stmt_seq*s=one_stmt_seq(st);if(!s)return -1;struct _mod mod={0};mod.kind=Module_kind;mod.v.Module.body=s;PyXIRFunction ir={0};int rc=_PyX_IR_FromAST(&mod,&ir);PyMem_Free(s->elements);PyMem_Free(s);if(rc<0)return -1;*out=ir.root;return 0;}
static stmt_ty transform_return(stmt_ty st,PyArena*arena){if(st->kind!=Return_kind)return st;expr_ty name=_PyAST_Name(PyUnicode_FromString("__pythonx_return__"),Load,st->lineno,st->col_offset,st->end_lineno,st->end_col_offset,arena);if(!name)return NULL;Py_ssize_t n=st->v.Return.value?1:0;asdl_expr_seq*args=_Py_asdl_expr_seq_new(n,arena);asdl_keyword_seq*kw=_Py_asdl_keyword_seq_new(0,arena);if(!args||!kw)return NULL;if(n)asdl_seq_SET(args,0,st->v.Return.value);expr_ty call=_PyAST_Call(name,args,kw,st->lineno,st->col_offset,st->end_lineno,st->end_col_offset,arena);if(!call)return NULL;return _PyAST_Expr(call,st->lineno,st->col_offset,st->end_lineno,st->end_col_offset,arena);}
static int compile_function_body(stmt_ty def,PyXIRNode**out){PyArena*arena=PyArena_New();if(!arena)return -1;Py_ssize_t n=asdl_seq_LEN(def->v.FunctionDef.body);asdl_stmt_seq*seq=_Py_asdl_stmt_seq_new(n,arena);if(!seq){PyArena_Free(arena);return -1;}for(Py_ssize_t i=0;i<n;i++){stmt_ty st=transform_return((stmt_ty)asdl_seq_GET(def->v.FunctionDef.body,i),arena);if(!st){PyArena_Free(arena);return -1;}asdl_seq_SET(seq,i,st);}struct _mod mod={0};mod.kind=Module_kind;mod.v.Module.body=seq;PyXIRFunction ir={0};int rc=_PyX_IR_FromAST(&mod,&ir);PyArena_Free(arena);if(rc<0)return -1;*out=ir.root;return 0;}
static PyObject *make_function(stmt_ty def,PyObject*globals){if(pyx_init_runtime()<0)return NULL;PyXIRNode*body=NULL;if(compile_function_body(def,&body)<0)return NULL;arguments_ty a=def->v.FunctionDef.args;Py_ssize_t npos=asdl_seq_LEN(a->posonlyargs)+asdl_seq_LEN(a->args);PyObject*pos=PyTuple_New(npos),*kwonly=PyTuple_New(asdl_seq_LEN(a->kwonlyargs)),*name=PyUnicode_FromString(def->v.FunctionDef.name);if(!pos||!kwonly||!name){Py_XDECREF(pos);Py_XDECREF(kwonly);Py_XDECREF(name);PyXIRFunction ir={body,NULL};_PyX_IR_Free(&ir);return NULL;}Py_ssize_t j=0;for(Py_ssize_t i=0;i<asdl_seq_LEN(a->posonlyargs);i++,j++)PyTuple_SET_ITEM(pos,j,Py_NewRef(((arg_ty)asdl_seq_GET(a->posonlyargs,i))->arg));for(Py_ssize_t i=0;i<asdl_seq_LEN(a->args);i++,j++)PyTuple_SET_ITEM(pos,j,Py_NewRef(((arg_ty)asdl_seq_GET(a->args,i))->arg));for(Py_ssize_t i=0;i<asdl_seq_LEN(a->kwonlyargs);i++)PyTuple_SET_ITEM(kwonly,i,Py_NewRef(((arg_ty)asdl_seq_GET(a->kwonlyargs,i))->arg));PyXFunctionObject*f=PyObject_New(PyXFunctionObject,&PyXFunction_Type);if(!f){Py_DECREF(pos);Py_DECREF(kwonly);Py_DECREF(name);PyXIRFunction ir={body,NULL};_PyX_IR_Free(&ir);return NULL;}f->globals=Py_NewRef(globals);f->name=name;f->positional=pos;f->kwonly=kwonly;f->vararg=a->vararg?Py_NewRef(a->vararg->arg):NULL;f->kwarg=a->kwarg?Py_NewRef(a->kwarg->arg):NULL;f->body=body;return(PyObject*)f;}
static PyObject *pyx_function_call(PyObject*self,PyObject*args,PyObject*kwargs){PyXFunctionObject*f=(PyXFunctionObject*)self;PyObject*locals=PyDict_Copy(f->globals);if(!locals)return NULL;Py_ssize_t nargs=PyTuple_GET_SIZE(args),npos=PyTuple_GET_SIZE(f->positional);if(nargs>npos&&!f->vararg){PyErr_Format(PyExc_TypeError,"%U() takes %zd positional arguments but %zd were given",f->name,npos,nargs);goto error;}for(Py_ssize_t i=0;i<nargs&&i<npos;i++)if(PyDict_SetItem(locals,PyTuple_GET_ITEM(f->positional,i),PyTuple_GET_ITEM(args,i))<0)goto error;if(f->vararg){PyObject*rest=PyTuple_GetSlice(args,npos,nargs);if(!rest||PyDict_SetItem(locals,f->vararg,rest)<0){Py_XDECREF(rest);goto error;}Py_DECREF(rest);}if(kwargs){PyObject*k,*v;Py_ssize_t p=0;while(PyDict_Next(kwargs,&p,&k,&v)){int known=PySequence_Contains(f->positional,k);if(known<0)goto error;int kwknown=PySequence_Contains(f->kwonly,k);if(kwknown<0)goto error;if((known||kwknown)&&PyDict_Contains(locals,k)){PyErr_Format(PyExc_TypeError,"%U() got multiple values for argument '%U'",f->name,k);goto error;}if(!known&&!kwknown&&!f->kwarg){PyErr_Format(PyExc_TypeError,"%U() got an unexpected keyword argument '%U'",f->name,k);goto error;}if(f->kwarg&&!known&&!kwknown){PyObject*d=PyDict_GetItem(locals,f->kwarg);if(!d){d=PyDict_New();if(!d||PyDict_SetItem(locals,f->kwarg,d)<0){Py_XDECREF(d);goto error;}Py_DECREF(d);}if(PyDict_SetItem(d,k,v)<0)goto error;}else if(PyDict_SetItem(locals,k,v)<0)goto error;}}}for(Py_ssize_t i=0;i<npos;i++)if(!PyDict_Contains(locals,PyTuple_GET_ITEM(f->positional,i))){PyErr_Format(PyExc_TypeError,"%U() missing required argument '%U'",f->name,PyTuple_GET_ITEM(f->positional,i));goto error;}for(Py_ssize_t i=0;i<PyTuple_GET_SIZE(f->kwonly);i++)if(!PyDict_Contains(locals,PyTuple_GET_ITEM(f->kwonly,i))){PyErr_Format(PyExc_TypeError,"%U() missing required keyword-only argument '%U'",f->name,PyTuple_GET_ITEM(f->kwonly,i));goto error;}PyObject*rf=PyCFunction_NewEx(&pyx_return_def,NULL,NULL);if(!rf||PyDict_SetItemString(locals,"__pythonx_return__",rf)<0){Py_XDECREF(rf);goto error;}Py_DECREF(rf);PyObject*r=_PyX_IR_Evaluate(f->body,locals);Py_DECREF(locals);if(r)return r;if(PyErr_ExceptionMatches(PyXReturnSignal)){PyObject*e=PyErr_GetRaisedException(),*a=PyException_GetArgs(e),*v=PyTuple_GET_SIZE(a)?Py_NewRef(PyTuple_GET_ITEM(a,0)):Py_NewRef(Py_None);Py_DECREF(a);Py_DECREF(e);return v;}return NULL;error:Py_DECREF(locals);return NULL;}
PyObject *_PyX_CompileASTToNative(mod_ty module){if(!module||module->kind!=Module_kind){PyErr_SetString(PyExc_TypeError,"PythonX native compilation requires a module AST");return NULL;}PyObject*globals=PyDict_New();if(!globals)return NULL;Py_ssize_t n=asdl_seq_LEN(module->v.Module.body);PyXIRNode*root=PyMem_Calloc(1,sizeof(*root));if(!root){Py_DECREF(globals);return PyErr_NoMemory();}root->op=PYX_IR_SEQUENCE;root->child_count=n;root->children=PyMem_Calloc((size_t)n,sizeof(*root->children));if(n&&!root->children){PyMem_Free(root);Py_DECREF(globals);return PyErr_NoMemory();}for(Py_ssize_t i=0;i<n;i++){stmt_ty st=(stmt_ty)asdl_seq_GET(module->v.Module.body,i);PyXIRNode*node=NULL;if(st->kind==FunctionDef_kind){PyObject*fn=make_function(st,globals);if(!fn)goto fail;node=PyMem_Calloc(1,sizeof(*node));if(!node){Py_DECREF(fn);goto fail;}node->op=PYX_IR_NAME_STORE;node->constant=PyUnicode_FromString(st->v.FunctionDef.name);node->left=PyMem_Calloc(1,sizeof(*node->left));if(!node->constant||!node->left){Py_XDECREF(node->constant);PyMem_Free(node->left);PyMem_Free(node);Py_DECREF(fn);goto fail;}node->left->op=PYX_IR_CONST;node->left->constant=fn;}else if(compile_stmt(st,&node)<0)goto fail;root->children[i]=node;}PyXIRFunction ir={root,globals};PyObject*native=_PyX_NativeCompileIR(&ir);Py_DECREF(globals);return native;fail:{PyXIRFunction ir={root,NULL};_PyX_IR_Free(&ir);Py_DECREF(globals);return NULL;}}
